### PR TITLE
Added a link to a blog post about data streaming with Apache Kafka

### PR DESCRIPTION
**Pull request by mikulskibartosz**
Hi,
I'm not sure if I can promote my own content, but I have written a guide about data streaming with Apache Kafka that is supposed to be useful for data engineers who are preparing for a job interview.

### CODE REVIEW

**Comment by baky0905** [comment]
@mikulskibartosz would you rather like to send it to the https://medium.com/plumbersofdatascience, I can add you as a writer and you can publish it there. Tell me if you would be interested.

**Comment by dematom** [comment]
a well explained article thanks for sharing

**Comment by mikulskibartosz** [comment]
@baky0905 sure, I can publish it there. My Medium account: https://medium.com/@mikulskibartosz

**Comment by baky0905** [comment]
@mikulskibartosz, I added you as a writer. Let me know if all is ok. Here are some [how-to contribute notes: ](https://medium.com/plumbersofdatascience/how-to-write-for-plumbers-of-data-science-c9d2adc67ee8)

**Comment by baky0905** [comment]
@mikulskibartosz  your post has been published so will close this pull request. Keep on the good work!

**Pull request closed without merging**
