### PR TITLE
make language more inclusive/generic

### PR DESCRIPTION
**Pull request by kenzshelley**

### CODE REVIEW

**Comment by biglovisa** [comment]
I was just about to put up a PR for this 👍 ✨

**Comment by andkret** [comment]
Thanks, but I'm not going to make these types of changes to how I talk and write.

**Comment by kenzshelley** [comment]
¯\_(ツ)_/¯ your repo, your decision. 

As a data engineer who isn't a guy, it stuck out to me when I skimmed the beginning of your doc. I sent the PR because I assumed that it was probably unintentional, and that you'd prefer not to potentially alienate a subset of the people who may be interested in reading your content.

**Comment by biglovisa** [comment]
As an aspiring data engineer who isn't a guy, I completely agree. Words and language matter. But - your repo, your decision.

**Comment by VikiAnn** [comment]
What a strange response to a kind gesture.

**Comment by rwarbelow** [comment]
@andkret out of curiosity, were you intending for your original wording to be male-specific?

**Comment by corneliusellen** [comment]
As an engineer who also isn't a guy who also used to say "guys" as synonymous with "people", I agree with this change. (Heck, I even used to say "you guyses!" - it's the oafish Midwesterner in me).

@andkret I don't think this PR is an attack on how you write and talk. It just seems like a grammatically correct and more inclusive suggestion to a public facing repo.

**Comment by robbkidd** [comment]
From the README:
> It's not only useful for beginners, professionals will definitely like the case study section.

"Engineers" is an improvement if the material is intended to appeal to more than male beginners and professionals. It's a simple change to accept and doesn't break the build.

**Comment by GeekOnCoffee** [comment]
As a guy, this is an easy change I've worked hard to make to be more inclusive. 

In this case, it would have been easier to hit the merge button than to type the response. I'd ask you to reconsider this simple change to make your language more inclusive.

**Comment by keithrbennett** [comment]
I've come to realize that sometimes something that isn't a big deal to me _is_ a big deal to someone else, because of their life experience. Also that sometimes something requiring very little effort for me can be disproportionately helpful to someone else. I would hope that you wouldn't look at this request as an imposition or censorship, but rather an opportunity to help your female colleagues feel valued and welcomed. They've asked very respectfully and nicely, and it seems to me that agreeing to their request would be a good thing for all individuals involved, and the community as a whole.

**Comment by ccompeau** [comment]
There is a community of people here who can make your work better and more widely appealing, basically for free. That is, if you’ll let them. This wasn’t a proposal for a substantial change to the main thrust of the work, and would have been simple enough to accept and have a happier audience. Why dig in and die on this particular hill? We all have blind spots. That’s ok. This is what editors are for - they can see what you can’t.

**Comment by robbkidd** [comment]
Imagine English is a dynamic, interpreted language. ( ... 🤔)

At least five users have reported that they are experiencing WARN-level deprecation messages when running your Cookbook. In their feminine English runtimes, the use of "guys" to refer to a group of people has been deprecated unless it is referring to a group of men. (This change has been validated on masculine runtimes where tests for "How many guys have you dated?" threw exceptions in enough of the tests that the deprecation has been adopted.)

It is true that the Cookbook still compiles and runs in their production environments. But the noise generated by the WARN messages is distracting to the operators trying to get benefit from your good work. 

One of the users has submitted a fix that worked for her English runtime. Four other users reported no WARN deprecation messages in their similar feminine runtimes. Four additional users reported that the fix does not break in their masculine runtimes. A one word change has made your Cookbook multi-platform.

"Closed, won't fix" for this seems like "Runs on my machine. I do not want to support feminine runtimes."

**Comment by armahillo** [comment]
This seems like such an obviously correct change it's weird to imagine anyone would complain about it.

Yes, the change is good; ship it :)

**Comment by benreyn** [comment]
Agree with all points here. As far as I can see it, this costs nothing and has a  net positive impact.

+1 LGTM 👍

**Comment by ejuten** [comment]
It looks like the term 'engineer' is used in the following paragraph, I like the consistency and inclusivity of that term throughout.

**Pull request closed without merging**
