### PR TITLE
Fix capitalization: JAva -> Java

### PR DESCRIPTION
**Pull request by plorenzatto**

### CODE REVIEW

**Comment by plorenzatto** [comment]
@andkret I think you were referring to `JSON Web Tokens`. Is that rigth?

**Comment by KenOwn** [comment]
<script>alert('hello，gaga!');</script>

**Comment by KenOwn** [comment]
<script>alert('hello，gaga!');</script>

**Comment by KenOwn** [comment]
<script>alert('hello，gaga!');</script>

**Comment by andkret** [comment]
Thanks I already replaced this with JSON, because Java was wrong here @plorenzatto

**Pull request closed without merging**
